In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df=pd.read_csv('/content/ecommerce-product-reviews.csv')

In [ ]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   review  5000 non-null   object
 1   label   5000 non-null   object
dtypes: object(2)
memory usage: 78.3+ KB

In [ ]:
df.head()

                                              review     label
0                   Law simply actually race it run.  positive
1  Fish help admit group gun real. Trial road tel...   neutral
2  Life standard score charge assume law.\nStatio...  positive
3  And perform edge data sea first. Something rev...   neutral
4  Animal interview huge activity some health deb...  negative

In [ ]:
from textblob import TextBlob
df['review']=df['review'].astype(str)
df['polarity_score']=df['review'].apply(lambda x:TextBlob(x).sentiment.polarity)
def categorize(score):
  if score>0.0:
    return 'Positive'
  elif score<0.0:
    return 'Negative'
  else:
    return 'Neutral'
df['sentiment analysis']=df['polarity_score'].apply(categorize)
print(df['sentiment analysis'].value_counts())

sentiment analysis
Positive    3501
Negative    1088
Neutral      411
Name: count, dtype: int64

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop=stopwords.words('english')
df['keywords']=df['review'].apply(lambda x:" ".join(x.lower() for x in x.split() if x not in stop and x.isalpha()))
df.head()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,review,label,polarity_score,sentiment analysis,keywords
0,Law simply actually race it run.,positive,0.00,Neutral,law simply actually race
1,Fish help admit group gun real. Trial road tel...,neutral,0.10,Positive,fish help admit group gun trial road televisio...
2,Life standard score charge assume law.\nStatio...,positive,0.00,Neutral,life standard score charge assume station evid...
3,And perform edge data sea first. Something rev...,neutral,0.04,Positive,and perform edge data sea something reveal pas...
4,Animal interview huge activity some health deb...,negative,0.16,Positive,animal interview huge activity health hold alw...

In [ ]:
from google.colab import files
df.to_csv('sentiment_analysis_final.csv',index=False)
files.download('sentiment_analysis_final.csv')